yarnPath: .yarn/releases/yarn-4.6.0.cjs
nmHoistingLimits: dependencies
nodeLinker: node-modules
supportedArchitectures:
  os:
    - current
    - win32
    - darwin
    - linux
  cpu:
    - current
    - arm64
    - x64
