import type { Metadata } from 'next';
import './globals.css';
import type { ReactNode } from 'react';
import Providers from '@/common/components/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const publicStreamServerUrl = process.env.PUBLIC_STREAM_SERVER_URL;
  if (!publicStreamServerUrl)
    throw new Error('PUBLIC_STREAM_SERVER_URL is not defined');

  // noinspection HtmlRequiredTitleElement,JSUnresolvedLibraryURL
  return (
    <html lang="en">
      <head>
        {process.env.NODE_ENV === 'development' && (
          <script
            async
            crossOrigin="anonymous"
            src="//unpkg.com/react-scan/dist/auto.global.js"
          />
        )}
      </head>
      <body className="antialiased">
        <Providers publicStreamServerUrl={publicStreamServerUrl}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
